
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-creds
  labels:
    heritage: drycc
type: Opaque
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
