
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-creds
  labels:
    heritage: drycc
type: Opaque
data:
{{- if eq .Values.global.prometheusLocation "off-cluster" }}
  url: {{ .Values.url | b64enc }}
{{- else }}
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
{{- end }}
