{{- if eq .Values.global.prometheusLocation "on-cluster" }}
{{- if (index .Values "kubeStateMetrics" "enabled") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drycc-kube-state-metrics
  labels:
    heritage: drycc
{{- end }}
{{- end }}
